"""Resolves the schemas/ and skills/ directories at runtime.

Two install modes read these directories, and neither can assume the other's
layout:

- Dev / editable install (`pip install -e .`, or running straight from a git
  checkout): schemas/ and skills/ live at the repo root, two/three levels up
  from the reading module -- the layout every other path in this codebase
  (and every test) already assumes.
- A real `pip install oah` from a built wheel: the repo root doesn't exist on
  the installed machine at all, only the oah/ package directory does. The
  wheel therefore bundles its own copy under oah/_bundled/, generated by
  scripts/sync_package_data.py right before `python -m build` runs (see
  .github/workflows/publish-pypi.yml) -- never committed, never hand-edited,
  so there is exactly one source of truth (the repo-root directories) and the
  bundled copy is just that source of truth's build-time snapshot.
"""
from pathlib import Path

_PACKAGE_ROOT = Path(__file__).parent


def resolve_dir(repo_root_name):
    """repo_root_name is 'schemas' or 'skills' -- both the repo-root
    directory name and the matching subdirectory name under oah/_bundled/."""
    dev_path = _PACKAGE_ROOT.parent / repo_root_name
    if dev_path.is_dir():
        return dev_path
    bundled_path = _PACKAGE_ROOT / "_bundled" / repo_root_name
    if bundled_path.is_dir():
        return bundled_path
    raise FileNotFoundError(
        f"could not find {repo_root_name!r} data at {dev_path} (dev/editable "
        f"install layout) or {bundled_path} (installed-wheel layout) -- this "
        f"install is missing its schema/skill data entirely"
    )
